### ISSUE TITLE
toolchain might be better to use armv8l  instead of armv7a

### ISSUE THREAD

**Issue by njhsi** [duhow/xiaoai-patch#11]
As I knew, on the same armv8 hardware, it'd be armv8l if kernel running in 64bit with 32bit sysroot(for userspace), and be armv7l if kernel in 32bit with 32bit sysroot.

Maybe I was wrong, but I checked in rokid projects for Amlogic a113x it was using armv8l gcc. btw, take a look on rokid yodaos, really interesting..

**Comment by duhow** [comment]
Feel free to create a PR with the toolchain setup to test 🙂
