### ISSUE TITLE
Help Install on Xiaomi Mi AI Speaker Mini LX01

### ISSUE THREAD

**Issue by Mybrc91** [duhow/xiaoai-patch#3]
I have a Xiaomi Mi AI Speaker Mini. Can you give me more detailed installation documentation? I don't know much about it. How can I login in to the device? Thank you.

**Comment by duhow** [comment]
Hi! You'll need to disassemble it and connect via TTL pins. Pins are at the button-facing part, so you need to remove all parts. Also GND soldering is quite hard, does not stick as easy as the others.

Once you're there, login with `root / tina`. Make a full image backup of all partitions.

Let me know when you're done :)

**Comment by Mybrc91** [comment]
> Hi! You'll need to disassemble it and connect via TTL pins. Pins are at the button-facing part, so you need to remove all parts. Also GND soldering is quite hard, does not stick as easy as the others.
> 
> Once you're there, login with `root / tina`. Make a full image backup of all partitions.
> 
> Let me know when you're done :)

I may have to give up on LX01 because I don't have the tools, would LX06 be easier or something else?

**Comment by duhow** [comment]
Same procedure. All speakers require physical disassemble and solder wires to get into shell and patch them.

**Comment by Mybrc91** [comment]
> Same procedure. All speakers require physical disassemble and solder wires to get into shell and patch them.

Okay,i will try to do it.
