### ISSUE TITLE
LX06 network configuration

### ISSUE THREAD

**Issue by KristijanL** [duhow/xiaoai-patch#66]
does anybody knows how to connect to my network via cli on LX06? i cant configure it via official app Mi Home do i need to use chines version?

Best Regards,
Kristijan

**Comment by duhow** [comment]
Use the command `wifi_connect` to configure wpa_supplicant and connect to a WPA Access Point.
If you're using latest `master` version, tap 5 times and use www.improv-wifi.com .

**Comment by KristijanL** [comment]
thanks! 
can i change the display name of the device? 
is bluetooth paring working, as i don't see my device via bluetooth, do i need to enable it?

**Comment by duhow** [comment]
7891df2cdaeb5ccec647ee06896ee5c00a7384de
