### ISSUE TITLE
mpg123 download error

### ISSUE THREAD

**Issue by zsf513** [duhow/xiaoai-patch#82]
mpg123 download failed, recommend using the official address: http://mpg123.orgis.org/download/mpg123-1.32.5.tar.bz2

**Comment by duhow** [comment]
`mpg123` is using `sourceforge.net` as location, and it should redirect to your best matching location (acting as CDN), so I would not change it for the moment.
https://github.com/duhow/xiaoai-patch/blob/c321532c64770ff4c32144721f0526079ffc49e1/packages/mpg123/package.mk#L3

I acknowledge there is this alternative, but even the author asks to use it as much as possible.

Please retry the download in another moment, or if you need it, change the location in your build package file.
