### ISSUE TITLE
support on arm64 host?

### ISSUE THREAD

**Issue by njhsi** [duhow/xiaoai-patch#9]
Thanks for the creative project!

Would you please also support the building env on arm64 machine? for instance I'd like to do the patch in a virtual machine of macOS M1. seems the host toolchain is for x86_64 only, it would be nice if aarch64 host is supported too.

**Comment by duhow** [comment]
Yikes... Don't have one to test that host arch.

I'll try to change build scripts to allow this change, but will need help building all packages on that arch, some may break or miss some specific setting.

**Comment by duhow** [comment]
Try this change and provide feedback and PR if needed to improve functionality.
